# Generated by Django 4.0.4 on 2022-06-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingstats', '0002_device_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=200)),
                ('event_severity_level', models.CharField(max_length=200)),
                ('event_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
