# Generated by Django 4.0.4 on 2022-06-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingstats', '0003_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
